language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - setup=basic

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - composer self-update
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run
  - vendor/bin/phpunit -c phpunit.xml.dist --verbose --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover
